### PR TITLE
bump geth 879 issue

### PR DESCRIPTION
**Pull request by InoMurko**
https://github.com/omisego/elixir-omg/issues/879

## Overview

Bump images and unlock geth RPC.
## Testing

Same tests should pass!

### CODE REVIEW

**Comment by unnawut** [comment]
Lets do it

**Comment by InoMurko** [comment]
I’m curious. How did bumping images in this pr block CI for everyone?

**Comment by InoMurko** [comment]
also thanks for merging @unnawut!

**Comment by unnawut** [comment]
> I’m curious. How did bumping images in this pr block CI for everyone?

This one https://github.com/omisego-images/docker-elixir-omg/issues/36

**Pull request merged**
