### PR TITLE
feat: bump to plasma-contracts@v1.0.4

### PR DESCRIPTION
**Pull request by unnawut**
## Overview

This PR bumps elixir-omg to [`plasma-contracts@v1.0.4`](https://github.com/omisego/plasma-contracts/releases/tag/v1.0.4) and updates the changelog in preparation for `elixir-omg@v0.4.5`.

## Changes

- Bump up to plasma-contracts@v1.0.4
- Update VERSION and CHANGELOG files

## Testing

- CI passes
- E2E tests are successful

### CODE REVIEW

**Comment by InoMurko** [comment]
docker forget docker-compose-watcher.yml! :)

**Comment by unnawut** [comment]
Good Inobot!

**Comment by unnawut** [comment]
Oh wait. But this is a contract change. Should we wait for contract deployment before updating its image tag and contract addrs?

**Comment by InoMurko** [comment]
I guess the whole bundle will change with this - so yeah.

**Comment by jbunce** [comment]
`v0.4.5-pre.0` when this lands will mean we can push out a new dev environment <3

**Comment by unnawut** [comment]
I'll be away from keyboard. Feel free to merge once it's approved. 🎉

**Pull request merged**
