### PR TITLE
Update alpine base image in Dockerfiles to v3.11

### PR DESCRIPTION
**Pull request by arthurk**
This PR updates the alpine docker base image to the latest version 3.11

The alpine release notes are available here https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases

## Testing

Docker build the images. CI should show us if this is successful.

### CODE REVIEW

**Comment by InoMurko** [comment]
We could test this now I think if you resolve the merge conflicts!

**Comment by unnawut** [comment]
@arthurk The error is a bit hidden behind "Start daemon services" step, probably because `docker-compose logs` returns a normal exit status. Something about missing OpenSSL so I think it's related to the alpine bump. Here's the relevant logs:

```shell
ERROR: for watcher  Container "7cae21c7e36b" is unhealthy.

ERROR: for watcher_info  Container "7cae21c7e36b" is unhealthy.
ERROR: Encountered errors while bringing up the project.
Makefile:12: recipe for target 'start_daemon_services' failed

...

childchain      | [load_failed,"Failed to load NIF library: 'Error loading shared library libcrypto.so.43: No such file or directory (needed by /app/lib/crypto-4.6.5/priv/lib/crypto.so)'","OpenSSL might not be installed on this system.\n"]
childchain      | "Unable to load crypto library. Failed with error:~n\"~p, ~s\"~n~s"
childchain      | {error_logger,error_msg}
childchain      | #{label=>{proc_lib,crash},report=>[[{initial_call,{supervisor,kernel,['Argument__1']}},{pid,<0.1349.0>},{registered_name,[]},{error_info,{exit,{on_load_function_failed,crypto},[{init,run_on_load_handlers,0,[]},{kernel,init,1,[{file,"kernel.erl"},{line,189}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,295}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}},{ancestors,[kernel_sup,<0.1335.0>]},{message_queue_len,0},{messages,[]},{links,[<0.1337.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,610},{stack_size,27},{reductions,265}],[]]}
childchain      | #{label=>{supervisor,start_error},report=>[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,{on_load_function_failed,crypto}},{offender,[{pid,undefined},{id,kernel_safe_sup},{mfargs,{supervisor,start_link,[{local,kernel_safe_sup},kernel,safe]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
childchain      | #{label=>{proc_lib,crash},report=>[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.1334.0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,crypto}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}},{ancestors,[<0.1333.0>]},{message_queue_len,1},{messages,[{'EXIT',<0.1335.0>,normal}]},{links,[<0.1333.0>,<0.1332.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,610},{stack_size,27},{reductions,193}],[]]}
childchain      | #{label=>{application_controller,exit},report=>[{application,kernel},{exited,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,crypto}}},{kernel,start,[normal,[]]}}},{type,permanent}]}
childchain      | {"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,crypto}}},{kernel,start,[normal,[]]}}}"}
childchain      |     args:     format:     label: 2020-04-10 04:55:13.081280 crash_report        2020-04-10 04:55:13.081327 supervisor_report   2020-04-10 04:55:14.083541 crash_report        2020-04-10 04:55:14.083735 std_info            Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,crypto}}},{kernel,start,[normal,[]]}}})
childchain      | 
```

I'll submit a separate PR to fix this silent failure.

**Comment by unnawut** [comment]
LGTM now. Thank you! Let's merge https://github.com/omisego-images/docker-elixir-omg/pull/40 and get the stable image tag onto this PR.

**Comment by unnawut** [comment]
Can use [`omisegoimages/elixir-omg-builder:stable-20200410`](https://hub.docker.com/layers/omisegoimages/elixir-omg-builder/stable-20200410/images/sha256-8c914793133d3b91750a4260dadb710c923dbd7686aa1395773b208daa7791c1?context=explore) now!

**Comment by arthurk** [comment]
@unnawut it's using the new stable image now

**Pull request merged**
