### PR TITLE
[elixir-omg] Add Dockerfile

### PR DESCRIPTION
**Pull request by jbunce**
Adds support for builds as far as needing `geth`.

To build:

`docker build -t plasma .`

To run:

`docker run -ti plasma`

### CODE REVIEW

**Comment by jbunce** [comment]
I need to fix a line in this. Please don't merge just yet.

**Comment by jbunce** [comment]
Ready for review

**Comment by Pongch** [comment]
Hi @jbunce Just for additional clarity- this dockerfile would cover the getting started steps until running `mix test` ? and I assume to run integration test you would just need a running geth node on a local machine- is this correct ?

**Comment by jbunce** [comment]
Yes will modify the README when this is a bit more streamlined for users

**Pull request merged**
