### PR TITLE
fix: add :jason and :omg as omg_watcher_info dependencies

### PR DESCRIPTION
**Pull request by unnawut**
## Overview

Fixes mix commands not working within `omg_watcher_info` subapp by adding `:jason` and `:omg` to `omg_watcher_info` subapp deps.

## Changes

@okalouti reported problems running ecto migration generation within the `omg_watcher_info` subapp. And this command needs to be run from the subapp.

```
$ mix ecto.gen.migration index_block_timestamp
==> omg_status
Compiling 1 file (.ex)
warning: found Jason in your application configuration
for Phoenix JSON encoding, but failed to load the library.

(module Jason is not available).

Ensure Jason exists in your deps in mix.exs,
and you have configured Phoenix to use it for JSON encoding by
verifying the following exists in your config/config.exs:

    config :phoenix, :json_library, Jason


  (phoenix) lib/phoenix.ex:40: Phoenix.start/2
  (kernel) application_master.erl:277: :application_master.start_it_old/4

==> omg_watcher_info
Compiling 25 files (.ex)

== Compilation error in file lib/omg_watcher_info/utxo_selection.ex ==
** (CompileError) lib/omg_watcher_info/utxo_selection.ex:25: module OMG.State.Transaction is not loaded and could not be found
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:208: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

The subapp uses `Jason` and `OMG.State.Transaction` but they are missing from `apps/omg_watcher_info/mix.exs` so they're not loaded when the subapp is started individually.

This PR adds `:jason` and `:omg` to the mixfile.

## Testing

Running this is now gives a successful migration response:

```
$ cd apps/omg_watcher_info
$ mix ecto.gen.migration some_new_migration_name
* creating priv/repo/migrations/20200130053905_some_new_migration_name.exs
```

### CODE REVIEW

**Comment by jrhite** [comment]
`mix ecto.gen.migration some_new_migration_name` --> `mix ecto.gen.migration some_new_migration_name -r OMG.WatcherInfo.DB.Repo`

You didn't need the `-r`?

Anyway, LGTM!

**Comment by unnawut** [comment]
> `mix ecto.gen.migration some_new_migration_name` --> `mix ecto.gen.migration some_new_migration_name -r OMG.WatcherInfo.DB.Repo`
> 
> You didn't need the `-r`?
> 
> Anyway, LGTM!

Yarp, I think this is because it's derived automatically:

> The repository must be set under `:ecto_repos` in the current app configuration or given via the `-r` option.
> https://hexdocs.pm/ecto_sql/Mix.Tasks.Ecto.Gen.Migration.html

From this line in [`apps/omg_watcher_info/config/config.exs`](https://github.com/omisego/elixir-omg/blob/master/apps/omg_watcher_info/config/config.exs#L8):

```elixir
ecto_repos: [OMG.WatcherInfo.DB.Repo]
```

**Comment by InoMurko** [comment]
wanna use https://hex.pm/packages/merkle_tree/2.0.0 in this PR?

**Comment by unnawut** [comment]
Need to bump https://github.com/omisego/ex_plasma first then followed by bumping both `:ex_plasma` and `:merkle_tree` in elixir-omg to avoid conflicting versions. I'll do those in separate PRs.

**Pull request merged**
