### PR TITLE
Feature/erc20 deposits demo

### PR DESCRIPTION
**Pull request by ebarakos**
The concept is to create a demo using ERC20 deposits instead of ETH. In terms of functionality, this one is similar to demo_01. More/different functionalities could be added. 

`fee_specs.json` needs to be changed manually.

Includes small fix on `mint` method.

### CODE REVIEW

**Comment by pdobacz** [comment]
Perfect! thank you @ebarakos, this looks flawless, just let us have the CI build&test (we're looking into why it hasn't already)

**Comment by pdobacz** [comment]
> (we're looking into why it hasn't already)

it hasn't because it was turned off :). @ebarakos, it's on now, but triggering seems to require a new commit. Would you be so kind to push a commit? Thank you and sorry about the hassle.

**Comment by ebarakos** [comment]
> > (we're looking into why it hasn't already)
> 
> it hasn't because it was turned off :). @ebarakos, it's on now, but triggering seems to require a new commit. Would you be so kind to push a commit? Thank you and sorry about the hassle.

It seems like it there is an issue of CI setup, something about the token in coveralls. Could it be because the code is lying in my own repo and the secret token is not setup there? Do you have any idea of how this can be solved? Thank you!

**Comment by ebarakos** [comment]
> > (we're looking into why it hasn't already)
> 
> it hasn't because it was turned off :). @ebarakos, it's on now, but triggering seems to require a new commit. Would you be so kind to push a commit? Thank you and sorry about the hassle.

Do we have any updates on this?

**Comment by pdobacz** [comment]
> Do we have any updates on this?

Hi @ebarakos, sorry for the wait. This is blocked on the coveralls/CircleCI problem, which we have on our list but it gets pushed back. I searched a bit, and there was no easy solution :(.

To speed things up I could probably open a branch & PR from `omisego` org, and pull your changes in, so that it builds fine. Does this work for you?

**Comment by ebarakos** [comment]
> > Do we have any updates on this?
> 
> Hi @ebarakos, sorry for the wait. This is blocked on the coveralls/CircleCI problem, which we have on our list but it gets pushed back. I searched a bit, and there was no easy solution :(.
> 
> To speed things up I could probably open a branch & PR from `omisego` org, and pull your changes in, so that it builds fine. Does this work for you?

Yes, let's try it. 

What do you think about this: You can create the feature/ERC20_deposits_demo branch out of master and I can PR on it. Then you merge it to master if/once the CI is passing.

**Comment by pdobacz** [comment]
> What do you think about this: You can create the feature/ERC20_deposits_demo branch out of master and I can PR on it

Yep, [the branch's up](https://github.com/omisego/elixir-omg/compare/feature/ERC20_deposits_demo?expand=1), feel free to open the PR. As you then update your branch, I'll just push to `omisego/branch` to update the PR.

**Comment by ebarakos** [comment]
OK, I see the changes are already incorporated, no need to open a new PR .
You can merge it to master when you are ready.

**Comment by pdobacz** [comment]
Hey @ebarakos. I had some time to look into this and started wondering why would the tests fail after your modification. I rebased on top of recent `master` and fixed the issue in https://github.com/omisego/elixir-omg/tree/feature/ERC20_deposits_demo, feel free to use this commit for your fork's branch and move forward with the PR (you'd have to make sure your demo still works as you intended though).

**Comment by pdobacz** [comment]
Hey @ebarakos, feel free to cherrypick c4ea5bd1b9f5372eb8d6bf7b235599e88c5e0f43, this should get the CI going (or just reset your branch to this commit - I built on top of your changes).

**Comment by ebarakos** [comment]
> Hey @ebarakos, feel free to cherrypick [c4ea5bd](https://github.com/omisego/elixir-omg/commit/c4ea5bd1b9f5372eb8d6bf7b235599e88c5e0f43), this should get the CI going (or just reset your branch to this commit - I built on top of your changes).

Thanks, I will try the next days.

**Comment by achiurizo** [comment]
There's been a quite a bit of changes since this PR so closing this as stale. Feel free to re-open ✨

**Pull request closed without merging**
