### PR TITLE
OMG-285 - wallet provider - gets N most recent transactions, optionally filtering by recipient

### PR DESCRIPTION
**Pull request by purbanow**

### CODE REVIEW

**Comment by kevsul** [comment]
This is probably outside the scope of this PD, but why is the filter by recipient? 
I mean, for a given address, when is it useful only to get the transactions where that address is the recipient? 
I think getting both sent and received transactions makes more sense (e.g. a wallet or block explorer would want to show both types of transaction)

**Comment by jarindr** [comment]
> This is probably outside the scope of this PD, but why is the filter by recipient?
> I mean, for a given address, when is it useful only to get the transactions where that address is the recipient?
> I think getting both sent and received transactions makes more sense (e.g. a wallet or block explorer would want to show both types of transaction)

actually it should be both send and received, maybe miscommunicated.

**Comment by kasima** [comment]
Seems like a miscommunication here. Let's change to filter by `address` and return both sent and received.

**Comment by purbanow** [comment]
Moved to #228 PR

**Pull request closed without merging**
