### PR TITLE
fix: mandatory limit

### PR DESCRIPTION
**Pull request by InoMurko**
## Overview

Swagger cannot generate optional parameters request body

## Changes
- Mandatory limit on get all transactions (it's dangerous to leave it without, we should also limit the amount!)

## Testing
@boolafish

### CODE REVIEW

**Comment by pnowosie** [comment]
Can you help me understand this :pr: a little better.
If I got it correctly API client generators we use don't handle optional parameters well?
Therefore to fix it, we're faking our documentation (API specs) - is it what this PR delivers?

**Comment by InoMurko** [comment]
Not really. This PR requires you to send a linit param in get all transactions because it’s a security issue to nit limit the response.

**Comment by jrhite** [comment]
☝️ absolutely. the backend should always enforce such things. client can ask for what it wants, but server validates/adjusts the constraints.

A minor thing, but IMHO, I hope we can improve our pagination handling, there is another for ticket for that: https://github.com/omisego/elixir-omg/issues/1215)

But specific to this ticket, I think it's not a good API user experience. The server validates and adjusts the limit. But there is no indication of this to the user. This can make them think there is a bug in our code or they did something wrong etc...

Returning a response with error message explaining that their pagination limit request exceeds the max limit of #### would be more useful and informative and less confusing to the API user.

**Comment by InoMurko** [comment]
I agree with @jrhite. 
@unnawut I think the server should set a cap on the limit param

Anyhow, this is mostly getting aroung swagger bugs that can’t handle all optional params in requesys

**Pull request merged**
