### PR TITLE
docs: changelog for v0.4.7 

### PR DESCRIPTION
**Pull request by unnawut**
## Overview

Update the changelog with changes from `v0.4.7-pre.0` to `v0.4.7-pre.1`

## Changes

- Update `CHANGELOG.md` for v0.4.7-pre.1

## Testing

N/A

### CODE REVIEW

**Comment by InoMurko** [comment]
can we squeeze this one in? https://github.com/omisego/elixir-omg/pull/1489

**Comment by InoMurko** [comment]
> You’re a hero

you too <3
image

**Comment by unnawut** [comment]
> can we squeeze this one in? #1489

Yup agree we should

**Comment by unnawut** [comment]
#1489 is merged to `v0.4`

**Pull request merged**
