### PR TITLE
fix: extract exits from contract in one call

### PR DESCRIPTION
**Pull request by InoMurko**
https://github.com/omisego/plasma-contracts/pull/468/files

## Overview

Pull SE in one contract call by passing an array of exit ids.
## Changes

- Will polish once contract PR is merged.

## Testing

Adapted.

### CODE REVIEW

**Comment by pdobacz** [comment]
see https://github.com/omisego/elixir-omg/compare/pdobacz/bump_contracts?expand=1 for a version that passes tests (at least locally, let's see what CI says).

Changes wrt this:
 - adapt to the other changes from the `master` contracts branch (1st commit)
 - adapt to the multi-getter change (2nd commit)
 - fix one issue (`exits` is a list not a map so `Map.values()` was not needed)
 - rename those functions (and IFE counterparts) to tidy an old naming mess. Needed to do that anyway, since the old name `get_standard_exit` was singular.

**Comment by pdobacz** [comment]
one remark to the above comment - this "conforming" only goes as far as bringing the existing integration up to speed. It touches but **doesn't solve completely** this issue https://github.com/omisego/elixir-omg/issues/1176, which can be considered part of full conformance.

**Comment by InoMurko** [comment]
@pdobacz you can close this when you don't need it anymore!

**Comment by pdobacz** [comment]
OK, when I get to it, I'll open a new PR from the branch and close this one, unless you beat me to it ofc

**Comment by InoMurko** [comment]
If this is still needed, please reopen. Tnx

**Pull request closed without merging**
