### PR TITLE
Adding automated dependency audits

### PR DESCRIPTION
**Pull request by okalouti**
Addresses https://github.com/omisego/elixir-omg/issues/1173

## Overview

Adding [mix_audit]() to dependencies and to the CI workflow.

## Changes

- `mix.exs` (root directory) and `mix.lock` adding `mix_audit`
-  Additions to `.circleci/config.yml` to add to CI workflow. 

## Testing

/

### CODE REVIEW

**Comment by okalouti** [comment]
Updated `mix_audit` to version `0.1.3` in order to remove warning about our earlier Elixir version. 
They fixed this issue after I requested: https://github.com/mirego/mix_audit/issues/3

**Comment by thec00n** [comment]
Does this PR include `Review all current dependencies`?

**Comment by okalouti** [comment]
Hi @thec00n. This PR does not remove unnecessary dependencies, but `mix_audit` reviews all dependencies in `mix.lock`

**Comment by okalouti** [comment]
Wondering if `audit_deps` becomes once this branch is merged to master? It isn't currently, but nothing in the`.circle` file that I see missing.

**Comment by mederic-p** [comment]
Approving, let's wait for Ino's review before merging tho.

**Comment by InoMurko** [comment]
The output of the audit is: “No vulnerabilities found.“

Seems a bit... simplistic. Can you give us an overview what it does? Maybe provide an example where and how it would yield ‘a hacker’!

**Comment by okalouti** [comment]
Hi @Ino. Sorry I realized I linked the wrong URL above. See [here](https://github.com/mirego/mix_audit) for details on the dependency.

```
How does it work?

MixAudit builds two lists when it’s executed in a project:

- A list of security advisories fetched from the community-maintained elixir-security-advisories repository
- A list of Mix dependencies from the various mix.lock files in the project

Then, it loops through each project dependency and tries to find security advisories that apply to it (through its package name) and that match its version specification (through the advisory patched and unaffected version policies).

If one is found, a vulnerability (the combination of a security advisory and a project dependency) is then added to the report.

The task will exit with a 0 status only if the report passes (ie. it reports no vulnerabilities). Otherwise, it will exit with a 1 status.
```

They show examples of what it looks like if a vulnerability is found. Not sure how we can "test" that though.

**Comment by InoMurko** [comment]
Cool @okalouti nice work. The security repo is here: https://github.com/dependabot/elixir-security-advisories/tree/master/packages

it's rather thin, hopefully that doesn't give us a false assumption our dependencies are all safe. It's a start of a process!

**Pull request merged**
