### PR TITLE
feature: set CAPTURE_LOG env var to unmute logs

### PR DESCRIPTION
**Pull request by InoMurko**
addresses the `chatty` part of https://github.com/omisego/elixir-omg/issues/1241
## Overview

If you
```
export CAPTURE_LOG=0
```
this would unmute your `mix test` invocation.

## Changes

- default mute logger

## Testing

 check the tests output

### CODE REVIEW

**Comment by unnawut** [comment]
Sounds good! One thing though...

```shell
# happy
$ CAPTURE_LOG=0 iex -e 'System.get_env("CAPTURE_LOG") |> if(do: false, else: true) |> IO.inspect(); System.halt()'
false

# sad
$ CAPTURE_LOG=1 iex -e 'System.get_env("CAPTURE_LOG") |> if(do: false, else: true) |> IO.inspect(); System.halt()'
false
```

**Comment by unnawut** [comment]
Following above, this solution is good enough imo. No need for fancy parsing.

```elixir
if(System.get_env("CAPTURE_LOG") == "1", do: true, else: false)
```

**Comment by InoMurko** [comment]
> ```shell
> if(System.get_env("CAPTURE_LOG") == "1", do: true, else: false
> ```

in this case, the default would be false... do we want the default to be false or true?

**Comment by unnawut** [comment]
The original intention is to mute log by default, no? Sounds good to me.

```elixir
$ CAPTURE_LOG=0 iex -e 'if(System.get_env("CAPTURE_LOG") == "1", do: true, else: false) |> IO.inspect(); System.halt()'
false 

$ CAPTURE_LOG=1 iex -e 'if(System.get_env("CAPTURE_LOG") == "1", do: true, else: false) |> IO.inspect(); System.halt()'
true

# disabled by default
$ iex -e 'if(System.get_env("CAPTURE_LOG") == "1", do: true, else: false) |> IO.inspect(); System.halt()'
false

# disabled by default
$ CAPTURE_LOG=inomurko iex -e 'if(System.get_env("CAPTURE_LOG") == "1", do: true, else: false) |> IO.inspect(); System.halt()'
false
```

**Comment by unnawut** [comment]
My original suggestion is to address the issue that `CAPTURE_LOG=0` and `CAPTURE_LOG=1` both result in muted logs.

**Comment by unnawut** [comment]
Okay I misunderstood that `CAPTURE_LOG=1` meant showing logs. It's actually the [opposite](https://hexdocs.pm/ex_unit/ExUnit.html#configure/1-options). Correction:

```elixir
if(System.get_env("CAPTURE_LOG") == "0", do: false, else: true
```

**Comment by InoMurko** [comment]
Sure! It would be good we have a solution we can all agree with. I personally don't mind logs printed during testing so this PR came more as a friendly response to @achiurizo request.

If this was an easy quick PR to get it over with I would gladly keep this open and maintain... I'll close this and @achiurizo if this is still a requirement for you open an issue where we can discuss it further. 
At the moment I think we all have priorities more urgent than this!

**Comment by InoMurko** [comment]
Oh yeah, the docker fixes ive extracted into https://github.com/omisego/elixir-omg/pull/1264/files pls review asap :D

**Pull request closed without merging**
